### PR TITLE
feat(timeline-server): Set Hbase 2.x profile version to Hbase 2.1.10 #3

### LINKED ISSUE #3: Set Hbase 2.x profile version to Hbase 2.1.10
In order to deploy Timeline Server V2 (see https://github.com/TOSIT-IO/tdp-collection/issues/623) Yarn Timeline Server has to be built using Hbase 2.1.10 to meet the deployed Hbase version.
Change the version of the available hbase hbase.profile=2.0 option from 2.0.0-beta1 to 2.1.10.

### PR DESCRIPTION
**Pull request by dapicard**
Add -Dhbase.profile=2.0 to build Timeline Server V2 with Hbase 2.1.10 support:

```
mvn -s .mvn/settings.xml clean install -Pdist -Dtar -Pnative -DskipTests -Dmaven.javadoc.skip=true -Dhbase.profile=2.0
```

### CODE REVIEW

**Comment by rpignolet** [comment]
@dapicard  thank you for your contribution to TDP!
In a fully open-source approach, all Issues/Pull Requests are fairly examined for integration.

A review process is in progress in order to validate this PR before merging. We will keep you updated as soon as possible.

Thank you again for your contribution to TDP.

**Comment by rpignolet** [comment]
I used https://github.com/TOSIT-IO/tdp-build-proxy-whitelist and the compilation is successful.

We are currently in a release phase so I don't know when we will merge it.

**Comment by dapicard** [comment]
> I used https://github.com/TOSIT-IO/tdp-build-proxy-whitelist and the compilation is successful.
> 
> We are currently in a release phase so I don't know when we will merge it.

The changes I made are only used if the flag -Dhbase.profile=2.0 is set. So merging it will not have any effect on the non hbase 2.0 profile. And if this PR is merged, maybe you could release the two profiles (hbase 1.x and hbase 2.x) with a classifier ?

**Comment by rpignolet** [comment]
Following the TDP 1.0 release, we made a new Hadoop repo here https://github.com/TOSIT-IO/hadoop. Can you open a new PR to the new repository please ?

**Comment by dapicard** [comment]
Done @rpignolet : https://github.com/TOSIT-IO/hadoop/pull/5

**Pull request closed without merging**
